// Jackson Coxson

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


/**
 * Starts your emotional damage
 * # Arguments
 * * `bind_addr` - The UDP socket to listen to
 * # Returns
 * A handle to stop further emotional damage.
 * Null on failure
 * # Safety
 * Don't be stupid
 */
void *start_emotional_damage(const char *bind_addr);

/**
 * Stops further emotional damage
 * # Arguments
 * * `handle` - The coping mechanism generated by start_emotional_damage
 * # Returns
 * The knowledge of knowing that you couldn't handle failure
 * # Safety
 * Don't be stupid
 */
void stop_emotional_damage(void *handle);
